### ISSUE TITLE
Clone marker and complexes

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#117]
There are 2 issues with clone marker for complexes:
1) Are subunits drawn on top of the complex. If so then this could obscure the identifier of the clone marker.
2) Can subunits be cloned? If so what does this mean? Presumably this must mean that they are cloned within the complex itself.

Reported by: stumoodie

**Comment by adrienrougny** [comment]
2) is still not specified explicitly in V2.0.

**Comment by hasanbalci** [comment]
What is the current status of this issue? As far as I observed:
- Labels part of Complex section states that the complex labels should not overlap with their subunits, but I did not see any statement stating that subunits should not overlap with clone markers. If we want to add such a statement, where should we add it?
- A statement exists emphasizing that subunits are auxiliary units decorating complex in L1 V2, but couldn't see any statement about whether they can be cloned or not. Should we add this to the text of Subunits section?

**Comment by hasanbalci** [comment]
To clarify that subunits should not obscure the clone marker of a complex, I changed the last sentence in Section 2.4.6 Glyph: Complex - Container from "The shapes of the subunits must not overlap." to "The shapes of the subunits must not overlap **with each other or with the clone marker of the complex, if it carries one.**"

In addition, to clarify that subunits cannot be cloned, I updated the statement in Section 2.3.4 Glyphs: Subunits as "Subunits do not represent or mimic entity pools (Section 2.4)**, so they cannot be cloned** and may only be used to represent the subunits included in a complex. "

**Comment by draeger** [comment]
https://github.com/sbgn/process-descriptions/issues/248

**Comment by draeger** [comment]
See https://github.com/sbgn/process-descriptions/issues/248
