### ISSUE TITLE
label on complexes

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#121]
We should add labels in complexes of the refcard.

Reported by: lenov

**Comment by adrienrougny** [comment]
Still not he case in V2.0.

**Comment by hasanbalci** [comment]
How is this? I can update the complex in the reference card this way.
![Complex_Label_Example](https://github.com/sbgn/process-descriptions/assets/22586369/ed4c4e92-278c-483d-8294-13a1432887da)

**Comment by hasanbalci** [comment]
I updated the related sentence in Section 2.4.5 Glyph: Complex - Label as follows: "In the case where the complex is described by a set of subunits, the label is **optional and** may be positioned to optimize the clarity and avoid overlapping, ideally between the bottom-most or the upper-most subunit and the border of the complex."

I also added label to the complex in reference card as we discussed in Editors' meeting (I added it to only outer one to show its optinality.)
<img width="213" alt="Screenshot 2024-09-04 at 07 20 11" src="https://github.com/user-attachments/assets/d9439976-605d-46a1-85df-e39bdc8e5579">
