### ISSUE TITLE
Phenotyp cloned in Fig. 2.5

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#122]
In SBGN PD 1.1, phenotype is a process node, and clone marker is used to when an EPN is duplicated.  In Fig. 2.5, the example shows the cloned phenotype.  I think it is from the old version when phenotype was still and EPN.

Huaiyu

Reported by: huaiyumi

**Comment by adrienrougny** [comment]
Not the case in V2.0 anymore.
