### ISSUE TITLE
Phenotype cloning?

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#124]
In the SBGN PD1.1 spec, it says phenotype can be cloned.
Cloning is only allowed for EPNs, isn't it?
If Phenotype is a Process Node, why can it have connections attached?

It would be helpful to have more examples how the phenotypes are used
in the actual pathway model.

Reported by: *anonymous

**Comment by adrienrougny** [comment]
Still inconsistent in V2.0 (table in section 3.5.3: Phenotype can be cloned; section 2.3.3: clone markers apply for EPNs only).

**Comment by hasanbalci** [comment]
I'm closing this issue because it is the duplicate of issue #209. Let's continue the discussion there.
