### ISSUE TITLE
balanced equations

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#126]
Section 3.5.2.1, page 43:
"5. The EPNs that make up the LHS of the process should be consistent with the RHS, i.e. the process should constitute a balanced biochemical reaction."
What is meant by that? Most graphical representations of pathways are not balanced. A simple example is the phosphorylation. This does not belong to SBGN. What goes on left and right is the choice of the map designer. I believe we should remove this item.

Reported by: lenov

**Comment by adrienrougny** [comment]
Still in V2.0

**Comment by hasanbalci** [comment]
I guess this issue is still open for discussion.

**Comment by adrienrougny** [comment]
Two possibilities: either leave the should or go through the specification and look at all versions of should, must, must not, should not.

From Key words for use in RFCs (https://datatracker.ietf.org/doc/html/rfc2119): "SHOULD"   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.
