### ISSUE TITLE
Example with empty state variables

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#131]
Neither in the spec nor in the examples on the website do-we have examples using empty state variables such as " @T" to represent a non-phosphorylated threonine. Only in the Nature Biotech do-we find those.

Reported by: lenov

**Comment by adrienrougny** [comment]
Still the case in the spec.

**Comment by hasanbalci** [comment]
In Figure 2.3, several variations of the glyph for state variable are shown. In that figure, we can either replace the middle-right one which is deprecated or add a new variation with "@var".

**Comment by hasanbalci** [comment]
I updated Figure 2.3 together with its caption by adding a new glyph with only name (the one in the middle).
