### ISSUE TITLE
compartment and submat, etc.

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#133]
In the ref card, container and reference node are used for compartment and submap.  In the spec, these two terms are not used.  Also, in Table 2.1, container node is used, and complex is an example of it.
Need to have a consistent nomenclature for these.

Reported by: huaiyumi

**Comment by adrienrougny** [comment]
Seems to no longer be the case: in the text, compartments are referred to as container nodes, and reference nodes are used to describe tags in the reference cards and in the text.
