### ISSUE TITLE
Unit of Information Identity

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#134]
I realise that the issue of Unit of Information identity has not really been discussed. In the spec the unit of information is treated as having instance identity (like process) which means that 2 UofI with the same content can be held by the same glyph. For example 2 identical cardinality labels or 2 UofIs with the same domain name could be displayed on the same EPN. We should clarify this.

Reported by: stumoodie

**Comment by hasanbalci** [comment]
I think we still don't have a statement that prevents two Unit of Informations with the same content on the same glyph. There is one for state variables in section 3.5 Semantic Rules - 3.5.1 EPNs. Maybe we can add a similar statement for UoIs as well: "All unit of informations associated with an Entity Pool Node should be unique and not duplicated within that node."

**Comment by hasanbalci** [comment]
In Editors' meeting we decided to add the statement in above comment and I added it to the Section 3.5 Semantic Rules - 3.5.1 EPNs.
