### ISSUE TITLE
Reorganise Glyoh Section

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#136]
Currenty the Gyoh section separates out the controlled vocabs, the monomeric EPNs and then has a separate section on multimers. It seems to me that this would be much easier to understand if we put all the information together. e.g.

Macromolecule

\- EPN descn

\- Possible material types

\- Multimer glyph

And so on for all the EPN types.

I think this would be clearer as all the relavtn information would be in one place.

Reported by: stumoodie

**Comment by adrienrougny** [comment]
Not implemented in V2.0
