### ISSUE TITLE
Subunit as a process

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#137]
This came up way back in Stanford. Should a subunit be classified as a type of process. I wasn't a fan at the time - still not, but it kind of makes sense. Also one can include a phenotype as a similar type of non-stiochiometric process. Candiated for inclusion in V2.0.

Reported by: stumoodie

**Comment by hasanbalci** [comment]
I think this idea is from a long time ago. It seems to me like an idea that won't have many supporters.

**Comment by adrienrougny** [comment]
I don't understand what would be the meaning of a subunit being a process.

**Comment by hasanbalci** [comment]
Needs more details to be considered.
