### ISSUE TITLE
Make mono and multi EPNs One "Glyph"

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#138]
Currently we distinguish beween monomer EPNs and their mulimer equivalents and treat them as completely separate entities. However, they are essentially the same "glyph", which is drawn differently depending on the cardinality value. It seems to make more sense to describe them as such within the specification rather than treating them differently.

Reported by: stumoodie

**Comment by adrienrougny** [comment]
Still in different sections in V2.0

**Comment by hasanbalci** [comment]
Is there still any change needed regarding this? If we are happy with its current state, I think we can close this issue.

**Comment by hasanbalci** [comment]
The motivation behind the issue is not clear, I am closing it.

**Comment by draeger** [comment]
I agree: A multimer is not the same as one of its monomers and should, consequently, be treeted as a separate entity.
