### ISSUE TITLE
Missing "state variable" from Section 3.4.2 PD L1V1.3

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#143]
I'm working on validating the libSBGN format. State variables are list as glyphs in both the specification and the libSBGN format, but they are not in the containment definition in Section 3.4.2 of PD L1V1.3, and it should be added.

Thanks,
Augustin Luna

Reported by: cannin

**Comment by adrienrougny** [comment]
Still there in V2.0.

**Comment by hasanbalci** [comment]
I think this was resolved at some point. State variable appears in the 3.4.2 Containment definition table.
