### ISSUE TITLE
Semantic rule "EPN must have an arc" is wrong

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#147]
The current version L1 V1.3 of the PD specification says in 3.5.1
"3. EPNs should not be orphaned (i.e. they must be associated with at least one
arc." I would read this as "EPNs must have an arc".

In a SBML model a species can be defined which is not part of a reaction.
If I want to visualize this SBML model in SBGN PD (most likely as EPN) I would have to remove this species to get a valid PD map because of the rule mentioned above.

Thus I think rule 3 of 3.5.1 is wrong and should be removed from the spec.

Reported by: tobicz

**Comment by hasanbalci** [comment]
@cannin Has any decision been made on this issue?

**Comment by hasanbalci** [comment]
Change must -> should.

**Comment by hasanbalci** [comment]
The final statement in the related section is now as follows: EPNs should not be orphaned (i.e. they should be associated with at least one arc).
