### ISSUE TITLE
PD:Node connectivity issues for logic arc and assoc / dissoc

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#148]
I discovered two issues in the Node connectivity section (3.4.1)

\* I believe that modulation (influence, stimulation, ...) should be allowed to point to the assoc / dissoc node. This is in fact the case in the Neuro-muscular junction example

\* I believe that logic arcs should be allowed to start at logic gates. so that more complex multi-layer boolean expressions can be built.

I'm a attaching illustrations.

Reported by: amarillion

**Comment by hasanbalci** [comment]
For the first point (which is same issue with #247), at the Editor's meeting, we decided to remove the restriction that prevented modulation arcs from being connected to assoc/dissoc nodes, as we believed that there might be situations where modulation arcs would need to be connected to these nodes. Accordingly, I updated the second table in "Section 3.4.1 Node connectivity".

For the second point, there was an inconsistency in the specifications. While the "Section 2.10.1 Glyph: Logic arc" allows logical operators to be source of logic arcs, the second table in "Section 3.4.1 Node connectivity" this is not indicated. So we decided to update the table to show that logic gates can be the source of logic arcs. I applied the required change in the table.
