### ISSUE TITLE
[draft L1V2] Subclasses vs type attribute

### ISSUE THREAD

**Issue by adrienrougny** [sbgn/process-descriptions#162]
Why do the Subunit, StoichiometricProcess, ModulationArc, FluxArc and LogicalOperator classes
have a type attribute rather than subclasses as the EntityPoolNode class? (this question can be in-
verted)

**Comment by Adrienrougny** [comment]
Moreover, FluxArc sometimes has a flux_type attribute, sometimes subclasses (ProductionArc and ConsumptionArc).
