### ISSUE TITLE
Best practices of drawing reversible enzyme-catalyzed reactions

### ISSUE THREAD

**Issue by draeger** [sbgn/process-descriptions#170]
In the past, the SBGN editors decided that drawing catalysis of reversible reactions was not permissible, as it can often be hardly distinguished which direction is favored by the catalysis. As it stands right now, the process should be duplicated in two irreversible processes, each one catalyzed by the enzyme. While the arguments for this are pretty clear and reasonable, it should be changed to a recommendation of best practices for the sake of usability.

Rationale: It can be expected that (a fraction of) users of SBGN will draw reversible arcs anyway for this. If SBGN software is restrictive and does not allow for reversible catalyzed reactions, users will be frustrated and go to Illustrator or other tools or even stop using SBGN at all and use another representation format in which they can draw this most easily. Furthermore, the preferred direction of catalysis may depend on the current state of the system, following Le Chatelier's principle, and can therefore dynamically change.

As a best practice, the specification would explain the rationale of splitting reversible catalyzed reactions and encourage drawing it this way. Furthermore, a validator could raise a warning when encountering this in an SBGN-ML graph. But users would still have the freedom to represent it in their favorite way.

**Comment by hasanbalci** [comment]
Maybe the current statement in section 2.6.1 on splitting reversible reactions can be changed as follows to make this requirement less strict: 

When such a reversible process is asymmetrically modulated, it ~~must~~should be represented by two different processes in a Process Description. **This approach is recommended to clearly distinguish the effects of asymmetric modulations on the process.** Figure 2.27 on the following page illustrates the use of two process nodes to represent the reversible activation of a G-protein coupled receptor. In the absence of any effector, an equilibrium exists between the inactive and active forms. The agonist stabilises the active form, while the inverse agonist stabilises the inactive form.

**Comment by cannin** [comment]
This issue does not arise when the reaction is symmetric see Figure 2.26
