### ISSUE TITLE
Integrate the rule following which there can be only one production arc with stoichiometry 1 outgoing an association?

### ISSUE THREAD

**Issue by adrienrougny** [sbgn/process-descriptions#181]

**Comment by hasanbalci** [comment]
Should this be added to Section 3.5.2.1 Flux Arcs?

**Comment by draeger** [comment]
Good question: Are there any cases amongst the thousands of biochemical reactions in nature where during an association a proton or other compound is being released? Generally, I'd say most likely an association means two compounds come together. But who knows what can be possible under whatever circumstances. Is there a need to be that strict?

**Comment by hasanbalci** [comment]
Deprecate at 2.1 and remove in next level.

**Comment by hasanbalci** [comment]
I added superscripts to the related items in second table in Section 3.4.1 Node connectivity with a footnote "Maximum one edge restriction in these cases is deprecated with this version." After the approval in Overleaf we can set the milestone of this issue as L2+.
