### ISSUE TITLE
tag and inverse tag glyphs; terminal and reverse terminal glyphs

### ISSUE THREAD

**Issue by amazein** [sbgn/process-descriptions#199]
For "tag" glyph we actually have two glyphs: the tag with the corner to the right and the inverse one. Is it specified in SBGN_ML? The same for "terminal" glyph.

**Comment by Adrienrougny** [comment]
Yes, it is specified using the "orientation" attribute, that can take either of the four values right, left, up and down, and that corresponds to where the glyph is pointing to.
