### ISSUE TITLE
Should reversible arcs be included in new V2?

### ISSUE THREAD

**Issue by adrienrougny** [sbgn/process-descriptions#200]
For now, the reversible arcs are defined as production arc. Should we include a new arc as in oldV2?

**Comment by amazein** [comment]
Do you mean it would be reversible consumption arc with the arrowhead pointing to the source? For that we would need to know the "official" direction?

**Comment by Adrienrougny** [comment]
Yes, in oldv2 it is a "consumption" reversible arc with the arrowhead pointing to the source. But I guess a "production" reversible arc with the arrowhead pointing to the target would work as well. This latter would maybe be more natural? In either case, I believe there would not be any "official" direction. Simply, nodes of the RHS are produced/consumed together, and it is the same for those of the LHS.

**Comment by Adrienrougny** [comment]
Editors' call 18/4/30: no new arc, but discuss reversible processes in the spec (in the process or the flux arc entry).
