### ISSUE TITLE
There is no introduction to the concept of modulation (sec 2.9.3)

### ISSUE THREAD

**Issue by Adrienrougny** [sbgn/process-descriptions#203]
Process nodes, EPNs, logical operators have their one subsection, and as a consequence, there is a brief introduction to those concepts.
It is not the case for modulations, which are all put in the Arcs section (2.9).
Should we add subsections to the Arcs section? (2.9.1: Flux arcs, 2.9.2 Modulations arcs,...)

**Comment by amazein** [comment]
Yes, the modulation arc is a tricky one. I have never had a chance to use this one yet. I guess it is for the cases when the effect depends on the concentration. For example, low concentration leads to stimulation and high concentration - to inhibition. I saw cases when students used it as sort-of "unknown"/"uncertain" arc, probably not what it was meant for. Some clarification would be nice.

**Comment by Adrienrougny** [comment]
I agree that the meaning of the modulation arc should be made more clear (and we should also check how it is defined in AF and ER).

But by modulations, I intended to talk about all modulation arcs (including stimulations, inhibitions...).
There is no subsection that groups all these arcs together.
