### ISSUE TITLE
The spec could be better standardized

### ISSUE THREAD

**Issue by adrienrougny** [sbgn/process-descriptions#206]
A number of elements could be better standardized, i.e. all written or drawn using the same word/style throughout the spec:
- label, container, and auxiliary entries
- style of SBGN in figures (e.g sometimes there is a space between nodes and arcs, sometimes not)
- legend of figures

**Comment by amazein** [comment]
I agree, it would be nice to unify the style, keep all the figures in different formats so they can be modified when needed.

**Comment by Adrienrougny** [comment]
Editors call 18/4/30: for figures, we should use SBGN-ED.
