### ISSUE TITLE
Can phenotype glyphs be cloned?

### ISSUE THREAD

**Issue by adrienrougny** [sbgn/process-descriptions#209]
In V1.3, phenotype, that is a process, could be cloned.
Now that processes have instance identity (voted), phenotype should not be cloned.
Should we enforce this? Make an exception?

**Comment by cannin** [comment]
This probably needs to go to the mailing list. The reason for having the clone markers is for things that get replicated on the diagrams, but I can't recall seeing a maps where phenotypes are widely cloned; I could be wrong. The DiseaseMaps group might be a good group to understand the importance of this feature.

**Comment by cannin** [comment]
* 3.5.3 Cloning table currently states that a clone marker should be used
* 3.3 Identifiable attributes (phenotypes in glyph description are stated as being identified by labels but not in 3.3

**Comment by hasanbalci** [comment]
See also #124 for a similar discussion on phenotype cloning.

**Comment by hasanbalci** [comment]
At the Editor's meeting we agreed that clone markers would not be used for Phenotype and decided to apply the same rules as Process in L1V2.1. However, this case will be discussed in more detail at the next level. Accordingly, I updated Table 3.2 Duplication rules.
