### ISSUE TITLE
Subsectioning of section 2 (Process Description Glyphs) could be improved

### ISSUE THREAD

**Issue by adrienrougny** [sbgn/process-descriptions#212]
Current sectioning is the following:

- Overview
- Controlled vocabularies...
   - ...
- Auxiliary Units
   - Unit of information
   - ...
- Entity pool nodes
   - Unspecified entity
   - ...
- Referring to other Nodes
   - Submap terminal/tag
- Defined sets of Entity Pool nodes
   - Compartment
- Encapsulation
   - Submap
- Process nodes
  - Process
  - ...
- Arcs
  - Consumption
  - Production
  - Modulation
  - Stimulation
  - ...
  - Logic arc
  - Equivalence arc
- Logical operators
  - And
  - Or
  - Not
  - Equivalence
- Annotation

I see a number of small issues, that could be solved easily:
1. The fact that all arcs are in the same section does not allow for proper introduction of modulation arcs. This section could be split: one section for flux arcs, one section for modulation arcs.
The equivalence arcs could be moved to section "Referring to other nodes". The logic arc could be moved to section "Logical operators".
2. The submap is introduced too soon, even before process nodes. As it is a complicated concept, rarely used, and, in a sense, makes the definition of a map recursive, I think it should be introduced at the end of section 2.
3. Section for annotation should look like others (every glyph is a subsubsection of a subsection). Subsection 2.11 could be renamed "Annotating node and arcs", and have one subsubsection that would be the annotation glyph.

I would be in favour of the following sectioning (changes are in bold):

- Overview
- Controlled vocabularies...
   - ...
- Auxiliary **u**nits
   - Unit of information
   - ...
- Entity pool nodes
   - Unspecified entity
   - ...
- Defined sets of **e**ntity **p**ool nodes
   - Compartment
- Process nodes
  - Process
  - ...
- **Flux arcs**
  - Consumption
  - Production
- **Modulation arcs**
  - Modulation
  - Stimulation
  - ...
- Logical operators
  - And
  - Or
  - Not
  - Equivalence
  - **Logic arc**
- **Annotating nodes and arcs**
  - Annotation
- Referring to other nodes
   - Submap terminal/tag
   - **Equivalence arc**
- **Encapsulation**
   - Submap

**Comment by sbgnbricks** [comment]
I like the separation of flux and modulation arcs. I am not sure about arcs section being inside of node sections (logical operators)... Seems inconsistent: sometimes they are in arc/edge sections and sometimes in node sections.

**Comment by amazein** [comment]
I like the separation of flux and modulation arcs. I am not sure about arcs section being inside of node sections (logical operators)... Seems inconsistent: sometimes they are in arc/edge sections and sometimes in node sections.

**Comment by draeger** [comment]
I agree. The change should be made.

**Comment by amazein** [comment]
Sounds good to me. We can offer this updated structure and then the community will comment. How would it look? Would they all be on the same level? Section "Equivalence arc" and then subsection "Equivalence arc" since the others are on the level of subsections?

**Comment by vtoure** [comment]
1. Flux arc: will this be a new 'term'? needs a definition? And we probably have to highlight this to the community when giving them the spec to be checked.

2. Some thoughts: 
- why not splitting into subsections the logical operators:
   * Logical operators
      * Logical nodes
         * and
         * ...
       * Logical arc
          * logic arc

- same for submap tag and equivalence arc: 
   * Referring to other nodes 
      * Reference node(s?)
         * submap terminal / tag
      * Reference arc
         * equivalence arc

Just some thoughts, I don't know if that would be a better structure but it might help on understanding which "particular" arcs connect to which nodes?
The rest looks good.
