### ISSUE TITLE
What is the Unit of Information label? 

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#215]
With figure 2.2: we do not know if the label is the whole text or if the whole text is pre$+$":"$+$label

**Comment by cannin** [comment]
@Adrienrougny good? The second one is correct. There are many tables with the column name "Label" that shows that the label is a combination of the a prefix and label text. 

I added this text: "Together, the prefix and label text constitute the label."

**Comment by Adrienrougny** [comment]
I still find it confusing to name a part of the label by the term label.
In the section 2.2 introducing the controlled vocabularies, the term "value" is used (e.g. "The values are to be taken from the Systems Biology Ontology"). Could we use this term? (e.g. "Together, the prefix and the value constitute the label.")

**Comment by cannin** [comment]
Went with this: 

Together, a prefix and a value constitute the label. The controlled vocabularies predefined
