### ISSUE TITLE
Breaking compatibility by deprecating symbol? 

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#217]
Is there a problem with: 

"This symbol is now \textbf{deprecated} in favor of the stadium symbol described above. New Process Description maps should not use the ellipse symbol."

Calling this a new level, I think there is no problem. Calling it a new version, I think so ... I think that the current draft needs to be cleaned up and then we figure out if that requires a version or level change.

**Comment by Adrienrougny** [comment]
I fully agree.

**Comment by adrienrougny** [comment]
This has been implemented in V2. The version vs level for these kind of modifications is still an issue though.

**Comment by cannin** [comment]
2024-05-30: During editors meeting. Level changes allow glyphs additions or removals. Version changes permit "deprecating" a glyph but allowing its continued use with the level/version.
