### ISSUE TITLE
The ``labelled X'' is not necessary in clone marker

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#220]
The ``labelled X'' is not necessary here (it is true if they do not have the same label. Remove it?)

**Comment by cannin** [comment]
The text is necessary because they do have the same label. I clarified the text. @Adrienrougny close this?

**Comment by cannin** [comment]
@Adrienrougny and remove overleaf comment.

**Comment by Adrienrougny** [comment]
I was just saying that a sufficient condition for two EPNs to be different is to belong to two different compartments (whether they share the same label or not). But it is not important, and your new text is fine for me.
