### ISSUE TITLE
Needs Vote? Can a labels be left empty?

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#221]
From my standpoint, the answer is no, but this might have been discussed earlier and there might already be an answer.

**Comment by Adrienrougny** [comment]
I have he same point of view. I will launch a discussion on sbgn-discuss.

**Comment by cannin** [comment]
4.3.2 Labels put that labels should be non-empty strings

**Comment by hasanbalci** [comment]
In Section 4.3.2 Labels, I replaced "Labels should be horizontal." by "Labels should be horizontal and non-empty strings."
