### ISSUE TITLE
"labelled" or "labeled" ?

### ISSUE THREAD

**Issue by Adrienrougny** [sbgn/process-descriptions#226]
**Target**

Specification

**Issue type**

Bug

**Bug report**

*Level and version*
Level: 1
Version: 2.0

*Section and page*
Section: whole document

*Bug description*
Sometimes "labelled", sometimes "labeled".

*Proposed solution*

**Comment by amazein** [comment]
I think we should stick with British English: labelled

**Comment by Adrienrougny** [comment]
Done
