### ISSUE TITLE
section for multimers is written as if multimer was a glyph

### ISSUE THREAD

**Issue by adrienrougny** [sbgn/process-descriptions#227]
**Target**

Specification

**Issue type**

Bug

**Bug report**

*Level and version*
Level: 1
Version: 2

*Section and page*
Section: 2.4.5 (Glyph: Multimer)
Page: 15

*Bug description*

The Multimer section is written as if _multimer_ was one glyph.
There are in fact multiple multimer glyphs. It should be better presented.

*Proposed solution*
Use the plural "multimers" in the section name and elsewhere, and maybe more rewriting.
Maybe add the following table with two columns (instead of figure 2.13?):

| Glyph name                   | Glyph                |
|------------------------------|----------------------|
| multimer of macromolecules   | drawing of the glyph |
| multimer of simple chemicals | drawing of the glyph |
| ...                          | ...                  |

**Comment by adrienrougny** [comment]
Only partially taken into account (table).

**Comment by hasanbalci** [comment]
I changed the section name to "Glyph: Multimers" and made a few small additions to the text to emphasize different types of multimers.

**Comment by hasanbalci** [comment]
We decided to change the title as Glyphs: Multimers.
