### ISSUE TITLE
Precisions about cardinality on production arc

### ISSUE THREAD

**Issue by amazein** [sbgn/process-descriptions#229]
Nicolas Le Novere:

Section 2.9.1 of SBGN PD L1 V1.3, on consumption arc, features a long description of the optional cardinality, and mention production arc. In section 2.9.2, on production arc, we have only "A cardinality label can be associated with a production arc indicating the stoichiometry of a process". Could we add:
"For more details, see the section describing the consumption arc". Alternatively, there could be section "Arc cardinality".

NB: In both consumption and production arc section, "the stoichiometry of a process" should be replaced by "the stoichiometry of the relevant EPN for the process".

**Comment by hasanbalci** [comment]
Added "For more details, see the section describing the consumption arc (Section 2.7.1)" to production arc section.

Replaced "the stoichiometry of a process" by "the stoichiometry of the relevant EPN for the process" in both consumption and production arc sections (Sections 2.7.1 and 2.7.2 in SBGN PD L1 V2.0)
