### ISSUE TITLE
Section 2.8.1 "Glyph: Modulation": replace "direction" by "sign" in descritption of the glyph

### ISSUE THREAD

**Issue by adrienrougny** [sbgn/process-descriptions#231]
**Target**

Specification

**Issue type**

Bug

**Bug report**

*Level and version*
Level: 1
Version: 2.0

*Section and page*
Section: 2.8.1
Page: 34

*Bug description*

"when one does not know the direction of the effect": should not be the direction, but rather the sign.

*Proposed solution*

Replace "direction" by "sign". Could also replace "direction of the effect" by "sign of the effect (stimulation or inhibition)"

**Comment by hasanbalci** [comment]
Replaced "direction of the effect" by "sign of the effect (stimulation or inhibition)".
