### ISSUE TITLE
Remove \corr{}{} found in files

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#240]
Currently there are many edits marked with \corr{TEXT_1}{TEXT_2} where TEXT_2 appears in the LV2.0 PDF. Remove the other text TEXT_1 when found? 

Example: 
https://github.com/sbgn/process-descriptions/blob/3f00082255e9a894f7e9b78fa707a4190e5fa754/Specifications/sources/or.tex#L4

Any thoughts on this @adrienrougny @tczauderna?

**Comment by cannin** [comment]
Similarly convert \rougny to issues or delete? There might be other \NAME 

https://github.com/sbgn/process-descriptions/blob/3f00082255e9a894f7e9b78fa707a4190e5fa754/Specifications/sources/and.tex#L8

**Comment by adrienrougny** [comment]
Yes they should all be deleted. I think I had made a script to remove all the \corr and \add, will check and remove them.

**Comment by cannin** [comment]
@adrienrougny if you have such a script maybe good to commit to some sbgn repo; we can discuss at next meeting

**Comment by hasanbalci** [comment]
It seems that such expressions have been removed.
