### ISSUE TITLE
After Merge with cleaning branch many images/examples missing

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#244]
Images for images/examples are missing after merge. Files available on backup: https://www.overleaf.com/project/66165297309c02dbcf07cb47

**Comment by adrienrougny** [comment]
I have moved all files from images/examples/ to src/images/, and changed their names to include "_example" at the end, in order to have a unique directory for the images.
In principle there should be no \includegraphics targeting a file in images/examples/ anymore; did you find one?

**Comment by hasanbalci** [comment]
I checked and couldn't find any reference to images/examples/. There seems to be no problem with the images.
