### ISSUE TITLE
Texts on some figures not fully visible

### ISSUE THREAD

**Issue by hasanbalci** [sbgn/process-descriptions#245]
**Target**

Specification

**Issue type**

Bug

**Bug report**

*Level and version*
Level: 1
Version: 2

Some figures have texts that are not fully visible. E.g.:
<img width="459" alt="Screenshot 2024-06-13 at 2 38 39 PM" src="https://github.com/sbgn/process-descriptions/assets/22586369/db41cf8d-d5b6-40c9-8929-69b18a859afb">

Such figures should be reviewed and improved.

Edit: In the specification document, I came across 3 figures in which the letters were not fully visible due to svg to pdf conversion: Figure 2.40, 2.60 and 2.61.

**Comment by adrienrougny** [comment]
This looks like an issue with the conversion from svg to pdf with inkscape, will look at it.

**Comment by hasanbalci** [comment]
I checked this again and if we try to open these svgs in browser they look good. However, if we open them in inkscape some letters are not fully visible. I think svg to pdf converter works correctly but problem is in the way inkscape evaluates these svgs.

**Comment by adrienrougny** [comment]
Fixed the three graphml source files and rebuilt the images.
