### ISSUE TITLE
Move the section about glyphs multimers below the section about the glyph complex

### ISSUE THREAD

**Issue by tczauderna** [sbgn/process-descriptions#246]
The section about the glyphs multimers explained all the different types of multimers. The complex is one of them.
Thus, the section about the glyph complex should come first.

**Comment by hasanbalci** [comment]
I moved the section "Glyphs: Multimers" below "Glyph: Complex" in document as suggested. Now, the order is
- 2.4.5 Glyph: Complex
- 2.4.6 Glyphs: Multimers
