### ISSUE TITLE
Misleading explanation of modulation arc targets

### ISSUE THREAD

**Issue by hasanbalci** [sbgn/process-descriptions#247]
**Target**

Specification

**Issue type**

Bug

**Bug report**

*Level and version*
Level: 1
Version: 2

*Section and page*
Section: 2.8 Modulation arcs

*Bug description*
In each subsection of modulation arcs (modulation, stimulation, catalysis, necessary stimulation and inhibition), target of the arc is explained as "One process node (Section 2.6)." However, as shown in the Arc/PN connectivity table in section 3.4.1 Node connectivity, modulation arcs cannot be connected to association and dissociation which are process nodes.  

*Proposed solution*
Target definitions can be updated as "One process node except association and dissociation (Section 2.6)." or we can remove the restriction in Arc/PN connectivity table.

**Comment by adrienrougny** [comment]
I would rather remove the constraint on modulation arcs targeting associations and dissociation processes since you can have such modulations that make sense (e.g., pH or adaptor proteins may influence complex formation).
I do not know the rationale behind this constraint though.

**Comment by hasanbalci** [comment]
@adrienrougny There is a similar suggestion in #148.

**Comment by hasanbalci** [comment]
At the Editor's meeting, we decided to remove this restriction, as we believed that there might be situations where modulation arcs would need to be connected to association and dissociation nodes. Accordingly, I updated the second table in Section 3.4.1 Node connectivity.
