### ISSUE TITLE
src/images/: simple_chemical_combined.graphml and production.graphml are empty files

### ISSUE THREAD

**Issue by adrienrougny** [sbgn/process-descriptions#252]
_simple_chemical_combined.graphml_ and _production.graphml_ files are empty.
They are also empty in the old overleaf project for V2.0.
Right now the _simple_chemical_combined.final.svg_ file used for the final image of the spec is a copy of _macromolecule_combined.final.svg_, so it should be changed when the original file is recovered.
As for _production.svg_ and _production.final.svg_, they are the right files.

**Comment by hasanbalci** [comment]
Please let's check it locally and if someone finds them upload here.

**Comment by adrienrougny** [comment]
Found them in an old commit of the v2.0 overleaf project and added them.
